// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/h3llascape/scan-split/internal/ocr.Provider -o provider_mock.go -n ProviderMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ProviderMock implements mm_ocr.Provider
type ProviderMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcRecognizeText          func(ctx context.Context, imageData []byte) (s1 string, err error)
	funcRecognizeTextOrigin    string
	inspectFuncRecognizeText   func(ctx context.Context, imageData []byte)
	afterRecognizeTextCounter  uint64
	beforeRecognizeTextCounter uint64
	RecognizeTextMock          mProviderMockRecognizeText
}

// NewProviderMock returns a mock for mm_ocr.Provider
func NewProviderMock(t minimock.Tester) *ProviderMock {
	m := &ProviderMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.RecognizeTextMock = mProviderMockRecognizeText{mock: m}
	m.RecognizeTextMock.callArgs = []*ProviderMockRecognizeTextParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mProviderMockRecognizeText struct {
	optional           bool
	mock               *ProviderMock
	defaultExpectation *ProviderMockRecognizeTextExpectation
	expectations       []*ProviderMockRecognizeTextExpectation

	callArgs []*ProviderMockRecognizeTextParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProviderMockRecognizeTextExpectation specifies expectation struct of the Provider.RecognizeText
type ProviderMockRecognizeTextExpectation struct {
	mock               *ProviderMock
	params             *ProviderMockRecognizeTextParams
	paramPtrs          *ProviderMockRecognizeTextParamPtrs
	expectationOrigins ProviderMockRecognizeTextExpectationOrigins
	results            *ProviderMockRecognizeTextResults
	returnOrigin       string
	Counter            uint64
}

// ProviderMockRecognizeTextParams contains parameters of the Provider.RecognizeText
type ProviderMockRecognizeTextParams struct {
	ctx       context.Context
	imageData []byte
}

// ProviderMockRecognizeTextParamPtrs contains pointers to parameters of the Provider.RecognizeText
type ProviderMockRecognizeTextParamPtrs struct {
	ctx       *context.Context
	imageData *[]byte
}

// ProviderMockRecognizeTextResults contains results of the Provider.RecognizeText
type ProviderMockRecognizeTextResults struct {
	s1  string
	err error
}

// ProviderMockRecognizeTextOrigins contains origins of expectations of the Provider.RecognizeText
type ProviderMockRecognizeTextExpectationOrigins struct {
	origin          string
	originCtx       string
	originImageData string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRecognizeText *mProviderMockRecognizeText) Optional() *mProviderMockRecognizeText {
	mmRecognizeText.optional = true
	return mmRecognizeText
}

// Expect sets up expected params for Provider.RecognizeText
func (mmRecognizeText *mProviderMockRecognizeText) Expect(ctx context.Context, imageData []byte) *mProviderMockRecognizeText {
	if mmRecognizeText.mock.funcRecognizeText != nil {
		mmRecognizeText.mock.t.Fatalf("ProviderMock.RecognizeText mock is already set by Set")
	}

	if mmRecognizeText.defaultExpectation == nil {
		mmRecognizeText.defaultExpectation = &ProviderMockRecognizeTextExpectation{}
	}

	if mmRecognizeText.defaultExpectation.paramPtrs != nil {
		mmRecognizeText.mock.t.Fatalf("ProviderMock.RecognizeText mock is already set by ExpectParams functions")
	}

	mmRecognizeText.defaultExpectation.params = &ProviderMockRecognizeTextParams{ctx, imageData}
	mmRecognizeText.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRecognizeText.expectations {
		if minimock.Equal(e.params, mmRecognizeText.defaultExpectation.params) {
			mmRecognizeText.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRecognizeText.defaultExpectation.params)
		}
	}

	return mmRecognizeText
}

// ExpectCtxParam1 sets up expected param ctx for Provider.RecognizeText
func (mmRecognizeText *mProviderMockRecognizeText) ExpectCtxParam1(ctx context.Context) *mProviderMockRecognizeText {
	if mmRecognizeText.mock.funcRecognizeText != nil {
		mmRecognizeText.mock.t.Fatalf("ProviderMock.RecognizeText mock is already set by Set")
	}

	if mmRecognizeText.defaultExpectation == nil {
		mmRecognizeText.defaultExpectation = &ProviderMockRecognizeTextExpectation{}
	}

	if mmRecognizeText.defaultExpectation.params != nil {
		mmRecognizeText.mock.t.Fatalf("ProviderMock.RecognizeText mock is already set by Expect")
	}

	if mmRecognizeText.defaultExpectation.paramPtrs == nil {
		mmRecognizeText.defaultExpectation.paramPtrs = &ProviderMockRecognizeTextParamPtrs{}
	}
	mmRecognizeText.defaultExpectation.paramPtrs.ctx = &ctx
	mmRecognizeText.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRecognizeText
}

// ExpectImageDataParam2 sets up expected param imageData for Provider.RecognizeText
func (mmRecognizeText *mProviderMockRecognizeText) ExpectImageDataParam2(imageData []byte) *mProviderMockRecognizeText {
	if mmRecognizeText.mock.funcRecognizeText != nil {
		mmRecognizeText.mock.t.Fatalf("ProviderMock.RecognizeText mock is already set by Set")
	}

	if mmRecognizeText.defaultExpectation == nil {
		mmRecognizeText.defaultExpectation = &ProviderMockRecognizeTextExpectation{}
	}

	if mmRecognizeText.defaultExpectation.params != nil {
		mmRecognizeText.mock.t.Fatalf("ProviderMock.RecognizeText mock is already set by Expect")
	}

	if mmRecognizeText.defaultExpectation.paramPtrs == nil {
		mmRecognizeText.defaultExpectation.paramPtrs = &ProviderMockRecognizeTextParamPtrs{}
	}
	mmRecognizeText.defaultExpectation.paramPtrs.imageData = &imageData
	mmRecognizeText.defaultExpectation.expectationOrigins.originImageData = minimock.CallerInfo(1)

	return mmRecognizeText
}

// Inspect accepts an inspector function that has same arguments as the Provider.RecognizeText
func (mmRecognizeText *mProviderMockRecognizeText) Inspect(f func(ctx context.Context, imageData []byte)) *mProviderMockRecognizeText {
	if mmRecognizeText.mock.inspectFuncRecognizeText != nil {
		mmRecognizeText.mock.t.Fatalf("Inspect function is already set for ProviderMock.RecognizeText")
	}

	mmRecognizeText.mock.inspectFuncRecognizeText = f

	return mmRecognizeText
}

// Return sets up results that will be returned by Provider.RecognizeText
func (mmRecognizeText *mProviderMockRecognizeText) Return(s1 string, err error) *ProviderMock {
	if mmRecognizeText.mock.funcRecognizeText != nil {
		mmRecognizeText.mock.t.Fatalf("ProviderMock.RecognizeText mock is already set by Set")
	}

	if mmRecognizeText.defaultExpectation == nil {
		mmRecognizeText.defaultExpectation = &ProviderMockRecognizeTextExpectation{mock: mmRecognizeText.mock}
	}
	mmRecognizeText.defaultExpectation.results = &ProviderMockRecognizeTextResults{s1, err}
	mmRecognizeText.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRecognizeText.mock
}

// Set uses given function f to mock the Provider.RecognizeText method
func (mmRecognizeText *mProviderMockRecognizeText) Set(f func(ctx context.Context, imageData []byte) (s1 string, err error)) *ProviderMock {
	if mmRecognizeText.defaultExpectation != nil {
		mmRecognizeText.mock.t.Fatalf("Default expectation is already set for the Provider.RecognizeText method")
	}

	if len(mmRecognizeText.expectations) > 0 {
		mmRecognizeText.mock.t.Fatalf("Some expectations are already set for the Provider.RecognizeText method")
	}

	mmRecognizeText.mock.funcRecognizeText = f
	mmRecognizeText.mock.funcRecognizeTextOrigin = minimock.CallerInfo(1)
	return mmRecognizeText.mock
}

// When sets expectation for the Provider.RecognizeText which will trigger the result defined by the following
// Then helper
func (mmRecognizeText *mProviderMockRecognizeText) When(ctx context.Context, imageData []byte) *ProviderMockRecognizeTextExpectation {
	if mmRecognizeText.mock.funcRecognizeText != nil {
		mmRecognizeText.mock.t.Fatalf("ProviderMock.RecognizeText mock is already set by Set")
	}

	expectation := &ProviderMockRecognizeTextExpectation{
		mock:               mmRecognizeText.mock,
		params:             &ProviderMockRecognizeTextParams{ctx, imageData},
		expectationOrigins: ProviderMockRecognizeTextExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRecognizeText.expectations = append(mmRecognizeText.expectations, expectation)
	return expectation
}

// Then sets up Provider.RecognizeText return parameters for the expectation previously defined by the When method
func (e *ProviderMockRecognizeTextExpectation) Then(s1 string, err error) *ProviderMock {
	e.results = &ProviderMockRecognizeTextResults{s1, err}
	return e.mock
}

// Times sets number of times Provider.RecognizeText should be invoked
func (mmRecognizeText *mProviderMockRecognizeText) Times(n uint64) *mProviderMockRecognizeText {
	if n == 0 {
		mmRecognizeText.mock.t.Fatalf("Times of ProviderMock.RecognizeText mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRecognizeText.expectedInvocations, n)
	mmRecognizeText.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRecognizeText
}

func (mmRecognizeText *mProviderMockRecognizeText) invocationsDone() bool {
	if len(mmRecognizeText.expectations) == 0 && mmRecognizeText.defaultExpectation == nil && mmRecognizeText.mock.funcRecognizeText == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRecognizeText.mock.afterRecognizeTextCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRecognizeText.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RecognizeText implements mm_ocr.Provider
func (mmRecognizeText *ProviderMock) RecognizeText(ctx context.Context, imageData []byte) (s1 string, err error) {
	mm_atomic.AddUint64(&mmRecognizeText.beforeRecognizeTextCounter, 1)
	defer mm_atomic.AddUint64(&mmRecognizeText.afterRecognizeTextCounter, 1)

	mmRecognizeText.t.Helper()

	if mmRecognizeText.inspectFuncRecognizeText != nil {
		mmRecognizeText.inspectFuncRecognizeText(ctx, imageData)
	}

	mm_params := ProviderMockRecognizeTextParams{ctx, imageData}

	// Record call args
	mmRecognizeText.RecognizeTextMock.mutex.Lock()
	mmRecognizeText.RecognizeTextMock.callArgs = append(mmRecognizeText.RecognizeTextMock.callArgs, &mm_params)
	mmRecognizeText.RecognizeTextMock.mutex.Unlock()

	for _, e := range mmRecognizeText.RecognizeTextMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmRecognizeText.RecognizeTextMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRecognizeText.RecognizeTextMock.defaultExpectation.Counter, 1)
		mm_want := mmRecognizeText.RecognizeTextMock.defaultExpectation.params
		mm_want_ptrs := mmRecognizeText.RecognizeTextMock.defaultExpectation.paramPtrs

		mm_got := ProviderMockRecognizeTextParams{ctx, imageData}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRecognizeText.t.Errorf("ProviderMock.RecognizeText got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRecognizeText.RecognizeTextMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.imageData != nil && !minimock.Equal(*mm_want_ptrs.imageData, mm_got.imageData) {
				mmRecognizeText.t.Errorf("ProviderMock.RecognizeText got unexpected parameter imageData, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRecognizeText.RecognizeTextMock.defaultExpectation.expectationOrigins.originImageData, *mm_want_ptrs.imageData, mm_got.imageData, minimock.Diff(*mm_want_ptrs.imageData, mm_got.imageData))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRecognizeText.t.Errorf("ProviderMock.RecognizeText got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRecognizeText.RecognizeTextMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRecognizeText.RecognizeTextMock.defaultExpectation.results
		if mm_results == nil {
			mmRecognizeText.t.Fatal("No results are set for the ProviderMock.RecognizeText")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmRecognizeText.funcRecognizeText != nil {
		return mmRecognizeText.funcRecognizeText(ctx, imageData)
	}
	mmRecognizeText.t.Fatalf("Unexpected call to ProviderMock.RecognizeText. %v %v", ctx, imageData)
	return
}

// RecognizeTextAfterCounter returns a count of finished ProviderMock.RecognizeText invocations
func (mmRecognizeText *ProviderMock) RecognizeTextAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRecognizeText.afterRecognizeTextCounter)
}

// RecognizeTextBeforeCounter returns a count of ProviderMock.RecognizeText invocations
func (mmRecognizeText *ProviderMock) RecognizeTextBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRecognizeText.beforeRecognizeTextCounter)
}

// Calls returns a list of arguments used in each call to ProviderMock.RecognizeText.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRecognizeText *mProviderMockRecognizeText) Calls() []*ProviderMockRecognizeTextParams {
	mmRecognizeText.mutex.RLock()

	argCopy := make([]*ProviderMockRecognizeTextParams, len(mmRecognizeText.callArgs))
	copy(argCopy, mmRecognizeText.callArgs)

	mmRecognizeText.mutex.RUnlock()

	return argCopy
}

// MinimockRecognizeTextDone returns true if the count of the RecognizeText invocations corresponds
// the number of defined expectations
func (m *ProviderMock) MinimockRecognizeTextDone() bool {
	if m.RecognizeTextMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RecognizeTextMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RecognizeTextMock.invocationsDone()
}

// MinimockRecognizeTextInspect logs each unmet expectation
func (m *ProviderMock) MinimockRecognizeTextInspect() {
	for _, e := range m.RecognizeTextMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProviderMock.RecognizeText at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRecognizeTextCounter := mm_atomic.LoadUint64(&m.afterRecognizeTextCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RecognizeTextMock.defaultExpectation != nil && afterRecognizeTextCounter < 1 {
		if m.RecognizeTextMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ProviderMock.RecognizeText at\n%s", m.RecognizeTextMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ProviderMock.RecognizeText at\n%s with params: %#v", m.RecognizeTextMock.defaultExpectation.expectationOrigins.origin, *m.RecognizeTextMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRecognizeText != nil && afterRecognizeTextCounter < 1 {
		m.t.Errorf("Expected call to ProviderMock.RecognizeText at\n%s", m.funcRecognizeTextOrigin)
	}

	if !m.RecognizeTextMock.invocationsDone() && afterRecognizeTextCounter > 0 {
		m.t.Errorf("Expected %d calls to ProviderMock.RecognizeText at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RecognizeTextMock.expectedInvocations), m.RecognizeTextMock.expectedInvocationsOrigin, afterRecognizeTextCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProviderMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockRecognizeTextInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProviderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProviderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockRecognizeTextDone()
}
