// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcessing() {
  return window['go']['app']['App']['CancelProcessing']();
}

export function GetOCRProvider() {
  return window['go']['app']['App']['GetOCRProvider']();
}

export function OpenResultsFolder(arg1) {
  return window['go']['app']['App']['OpenResultsFolder'](arg1);
}

export function ProcessFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['ProcessFile'](arg1, arg2, arg3);
}

export function SelectInputFile() {
  return window['go']['app']['App']['SelectInputFile']();
}

export function SelectOutputDir() {
  return window['go']['app']['App']['SelectOutputDir']();
}
