// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcessing():Promise<void>;

export function GetOCRProvider():Promise<string>;

export function OpenResultsFolder(arg1:string):Promise<void>;

export function ProcessFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectInputFile():Promise<string>;

export function SelectOutputDir():Promise<string>;
